//
//  AllSenators.swift
//  citizenship-quiz
//
//  Created by Mike Williams on 3/5/25.
//

// AllSenators.swift
import Foundation

struct AllSenators {
    static let all: [String] = [
        "Tommy Tuberville",
        "Katie Britt",
        "Lisa Murkowski",
        "Dan Sullivan",
        "Kyrsten Sinema",
        "Mark Kelly",
        "John Boozman",
        "Tom Cotton",
        "Alex Padilla",
        "Laphonza Butler",
        "Mike Braun",
        "Mitt Romney",
        "Cory Booker",
        "Bob Menendez",
        "John Hickenlooper",
        "Michael Bennet",
        "Chris Murphy",
        "Chris Coons",
        "Tom Carper",
        "Rick Scott",
        "Mike Lee",
        "Jon Ossoff",
        "Raphael Warnock",
        "Brian Schatz",
        "Mazie Hirono",
        "Mike Crapo",
        "Jim Risch",
        "Dick Durbin",
        "Tammy Duckworth",
        "Todd Young",
        "Chuck Grassley",
        "Joni Ernst",
        "Jerry Moran",
        "Roger Marshall",
        "Mitch McConnell",
        "Rand Paul",
        "Bill Cassidy",
        "John Kennedy",
        "Susan Collins",
        "Angus King",
        "Ben Cardin",
        "Chris Van Hollen",
        "Elizabeth Warren",
        "Ed Markey",
        "Debbie Stabenow",
        "Gary Peters",
        "Amy Klobuchar",
        "Tina Smith",
        "Roger Wicker",
        "Cindy Hyde-Smith",
        "Josh Hawley",
        "Eric Schmitt",
        "Jon Tester",
        "Steve Daines",
        "Deb Fischer",
        "Ben Sasse",
        "Jacky Rosen",
        "Catherine Cortez Masto",
        "Jeanne Shaheen",
        "Maggie Hassan",
        "Bob Casey Jr.",
        "John Fetterman",
        "Cynthia Lummis",
        "John Barrasso",
        "Sherrod Brown",
        "Bernie Sanders",
        "Patrick Leahy",
        "Tim Kaine",
        "Mark Warner",
        "Patty Murray",
        "Maria Cantwell",
        "Joe Manchin",
        "Shelley Moore Capito",
        "Ron Johnson",
        "Tammy Baldwin",
        "Marsha Blackburn",
        "Bill Hagerty",
        "Ted Cruz",
        "John Cornyn",
        "Ron Wyden",
        "Jeff Merkley",
        "Chuck Schumer",
        "Kirsten Gillibrand",
        "Thom Tillis",
        "Ted Budd",
        "Kevin Cramer",
        "John Hoeven",
        "Jim Inhofe",
        "James Lankford",
        "Kate Brown",       
        "Earl Blumenauer",
        "Tom Cotton",
        "John Boozman",
        "Richard Burr",
        "Pat Toomey",
        "Marco Rubio",
        "Mike Rounds",
        "Tim Scott",
        "Richard Shelby",
        "Pat Roberts",
        "Ben Ray Luján",
        "Martin Heinrich",
        "Roy Blunt",
        "Lamar Alexander",
        "Lindsey Graham"
    ]
}
